(ns my-app.app.core
  (:require [reagent.dom :as rdom]))

;; --- Component Views ---

(defn header []
  [:div {:style {:display "flex" :align-items "center"}}
   [:img {:src "/img/cljs.png" :width 120}]
   [:h1 {:style {:padding "1rem" :font-weight "bold"}} "Create Reagent App"]])

(defn description []
  [:p {:style {:padding-top "2rem"}}
   "Bootstrap a ClojureScript frontend app that uses "
   [:a {:href "https://github.com/reagent-project/reagent" :target "_blank"} "Reagent"]
   " for your user interface and "
   [:a {:href "http://shadow-cljs.org/" :target "_blank"} "Shadow-CLJS"]
   " as its build tool / compiler."])

(defn aside []
  [:aside {:style {:padding-top "2rem" :font-weight "lighter" :line-height "1.4rem"}}
   "Note that the CLJS image on this page is in the " [:code "/public/img"] " folder, "
   "and the CSS stylesheet is in the " [:code "/public/css"] " folder. "
   "Feel free to edit the CSS stylesheet and images in" [:code "/public"] ". Only the "
   [:code "/public/js"] " folder is generated by the compiler, and should "
   [:span {:style {:font-weight "bolder"}} "not"] " be edited directly."])

(defn app []
  [:div.wrapper  ;; wrapper is shorthand for {:class "wrapper"}
   [header]
   [description]
   [aside]])

;; --- Render App ---

(defn render []
  (rdom/render [app] (.getElementById js/document "root")))

(defn ^:export main []
  (println "Initial render")
  (render))

(defn ^:dev/after-load reload! []
  (println "Reload!")
  (render))
