(ns *|USER-PROJECT-NAME|*.app.views.aside)

(defn aside []
  [:aside {:style {:padding-top "2rem" :font-weight "lighter" :line-height "1.4rem"}}
   "Note that CSS stylesheet is in the " [:code "/public/css"] " folder. "
   "Feel free to edit it. Only the "
   [:code "/public/js"] " folder is generated by the compiler, and should "
   [:span {:style {:font-weight "bolder"}} "not"] " be edited directly."])
